### ISSUE TITLE
KeepKey missing from list of hardware wallets

### ISSUE THREAD

**Issue by patrikr** [bchinfo/bch.info#61]
KeepKey is missing from the list of hardware wallets. Is this on purpose or an oversight?

**Comment by imaginaryusername** [comment]
Likely an oversight, consulting the team now.

**Comment by merc1er** [comment]
I am hearing a lot of negative feedback on KeepKey (for example https://www.reddit.com/r/keepkey/comments/7j3504/keepkey_stuck_at_loading_accounts/).

I don't think we should list it until the new manager client comes out of beta.

**Comment by patrikr** [comment]
Hmm, OK, but if the official software sucks you can use Electron Cash instead, right? (Also, that reddit thread is three years old.)

I just find it a bit peculiar that you are listing Trezor and Ledger who are hostile towards BCH, but not KeepKey who AFAIK are neutral.

**Comment by greatwolf** [comment]
I'm reviving this issue. KeepKey does have BitcoinCash support. There are several ways to access bch on a Keepkey: through beta.shapeshift.com, using Electrum fork ElectronCash, or through [KKClient](https://github.com/greatwolf/KKClient) which is a fork I did of the original Chrome Extension, a project I took up maintaining since the original Shapeshift KeepKey devs dropped support.

**Comment by merc1er** [comment]
Closing this as KeepKey was added to the wallets list: https://bch.info/en/wallets
